# Generated by Django 5.1.1 on 2024-10-07 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_password_hint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password_hint',
        ),
    ]
