# Generated by Django 5.1.1 on 2024-10-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_password_hint'),
    ]

    operations = [
        migrations.CreateModel(
            name='recent_search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent_0', models.CharField(blank=True, max_length=30)),
                ('recent_1', models.CharField(blank=True, max_length=30)),
                ('recent_2', models.CharField(blank=True, max_length=30)),
                ('recent_3', models.CharField(blank=True, max_length=30)),
                ('recent_4', models.CharField(blank=True, max_length=30)),
                ('recent_5', models.CharField(blank=True, max_length=30)),
                ('recent_6', models.CharField(blank=True, max_length=30)),
                ('recent_7', models.CharField(blank=True, max_length=30)),
                ('recent_8', models.CharField(blank=True, max_length=30)),
                ('recent_9', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
