# Generated by Django 5.1.1 on 2024-10-09 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_recent_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='recent_search',
        ),
    ]
